"""add_saved_reports_table

Revision ID: 8eaf5d77044d
Revises: e2c1eab0cc6f
Create Date: 2026-09-19 17:19:31.863460

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eaf5d77044d'
down_revision: Union[str, None] = 'e2c1eab0cc6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('filters_json', sa.JSON(), nullable=False),
    sa.Column('columns_json', sa.JSON(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_reports_created_by_id'), 'saved_reports', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_saved_reports_report_type'), 'saved_reports', ['report_type'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_reports_report_type'), table_name='saved_reports')
    op.drop_index(op.f('ix_saved_reports_created_by_id'), table_name='saved_reports')
    op.drop_table('saved_reports')
    # ### end Alembic commands ###
