"""006_communications_external_integrations

Revision ID: e2c1eab0cc6f
Revises: 4377746884bd
Create Date: 2026-09-19 11:41:10.430327

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c1eab0cc6f'
down_revision: Union[str, None] = '4377746884bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('account_sid', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('encrypted_auth_token', sa.Text(), nullable=True),
    sa.Column('webhook_secret', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whatsapp_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('phone_number_id', sa.String(length=100), nullable=True),
    sa.Column('business_account_id', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('webhook_verify_token', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communication_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_templates_channel'), 'communication_templates', ['channel'], unique=False)
    op.create_index(op.f('ix_communication_templates_is_active'), 'communication_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_communication_templates_name'), 'communication_templates', ['name'], unique=True)
    op.create_table('email_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('history_id', sa.String(length=100), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_accounts_email_address'), 'email_accounts', ['email_address'], unique=True)
    op.create_index(op.f('ix_email_accounts_status'), 'email_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_email_accounts_user_id'), 'email_accounts', ['user_id'], unique=False)
    op.create_table('email_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_thread_id', sa.String(length=150), nullable=False),
    sa.Column('email_account_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('college_id', sa.String(length=36), nullable=True),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('opportunity_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('ticket_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_account_id'], ['email_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_threads_college_id'), 'email_threads', ['college_id'], unique=False)
    op.create_index(op.f('ix_email_threads_contact_id'), 'email_threads', ['contact_id'], unique=False)
    op.create_index(op.f('ix_email_threads_email_account_id'), 'email_threads', ['email_account_id'], unique=False)
    op.create_index(op.f('ix_email_threads_invoice_id'), 'email_threads', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_email_threads_is_archived'), 'email_threads', ['is_archived'], unique=False)
    op.create_index(op.f('ix_email_threads_is_deleted'), 'email_threads', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_email_threads_is_read'), 'email_threads', ['is_read'], unique=False)
    op.create_index(op.f('ix_email_threads_last_message_at'), 'email_threads', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_email_threads_lead_id'), 'email_threads', ['lead_id'], unique=False)
    op.create_index(op.f('ix_email_threads_opportunity_id'), 'email_threads', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_email_threads_project_id'), 'email_threads', ['project_id'], unique=False)
    op.create_index(op.f('ix_email_threads_provider_thread_id'), 'email_threads', ['provider_thread_id'], unique=True)
    op.create_index(op.f('ix_email_threads_ticket_id'), 'email_threads', ['ticket_id'], unique=False)
    op.create_table('communication_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('email_account_id', sa.String(length=36), nullable=True),
    sa.Column('thread_id', sa.String(length=36), nullable=True),
    sa.Column('provider_message_id', sa.String(length=150), nullable=True),
    sa.Column('provider_thread_id', sa.String(length=150), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('cc', sa.Text(), nullable=True),
    sa.Column('bcc', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('call_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('call_disposition', sa.String(length=100), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('college_id', sa.String(length=36), nullable=True),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('opportunity_id', sa.String(length=36), nullable=True),
    sa.Column('sales_order_id', sa.String(length=36), nullable=True),
    sa.Column('contract_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('project_task_id', sa.String(length=36), nullable=True),
    sa.Column('ticket_id', sa.String(length=36), nullable=True),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('vendor_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['email_account_id'], ['email_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['customer_payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_task_id'], ['project_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_messages_channel'), 'communication_messages', ['channel'], unique=False)
    op.create_index(op.f('ix_communication_messages_college_id'), 'communication_messages', ['college_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_contact_id'), 'communication_messages', ['contact_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_contract_id'), 'communication_messages', ['contract_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_direction'), 'communication_messages', ['direction'], unique=False)
    op.create_index(op.f('ix_communication_messages_email_account_id'), 'communication_messages', ['email_account_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_invoice_id'), 'communication_messages', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_is_deleted'), 'communication_messages', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_communication_messages_lead_id'), 'communication_messages', ['lead_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_opportunity_id'), 'communication_messages', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_payment_id'), 'communication_messages', ['payment_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_project_id'), 'communication_messages', ['project_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_project_task_id'), 'communication_messages', ['project_task_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_provider_message_id'), 'communication_messages', ['provider_message_id'], unique=True)
    op.create_index(op.f('ix_communication_messages_provider_thread_id'), 'communication_messages', ['provider_thread_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_recipient'), 'communication_messages', ['recipient'], unique=False)
    op.create_index(op.f('ix_communication_messages_sales_order_id'), 'communication_messages', ['sales_order_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_sender'), 'communication_messages', ['sender'], unique=False)
    op.create_index(op.f('ix_communication_messages_status'), 'communication_messages', ['status'], unique=False)
    op.create_index(op.f('ix_communication_messages_thread_id'), 'communication_messages', ['thread_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_ticket_id'), 'communication_messages', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_communication_messages_vendor_id'), 'communication_messages', ['vendor_id'], unique=False)
    op.create_table('communication_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['communication_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_attachments_message_id'), 'communication_attachments', ['message_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communication_attachments_message_id'), table_name='communication_attachments')
    op.drop_table('communication_attachments')
    op.drop_index(op.f('ix_communication_messages_vendor_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_ticket_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_thread_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_status'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_sender'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_sales_order_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_recipient'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_provider_thread_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_provider_message_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_project_task_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_project_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_payment_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_opportunity_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_lead_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_is_deleted'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_invoice_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_email_account_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_direction'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_contract_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_contact_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_college_id'), table_name='communication_messages')
    op.drop_index(op.f('ix_communication_messages_channel'), table_name='communication_messages')
    op.drop_table('communication_messages')
    op.drop_index(op.f('ix_email_threads_ticket_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_provider_thread_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_project_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_opportunity_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_lead_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_last_message_at'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_is_read'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_is_deleted'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_is_archived'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_invoice_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_email_account_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_contact_id'), table_name='email_threads')
    op.drop_index(op.f('ix_email_threads_college_id'), table_name='email_threads')
    op.drop_table('email_threads')
    op.drop_index(op.f('ix_email_accounts_user_id'), table_name='email_accounts')
    op.drop_index(op.f('ix_email_accounts_status'), table_name='email_accounts')
    op.drop_index(op.f('ix_email_accounts_email_address'), table_name='email_accounts')
    op.drop_table('email_accounts')
    op.drop_index(op.f('ix_communication_templates_name'), table_name='communication_templates')
    op.drop_index(op.f('ix_communication_templates_is_active'), table_name='communication_templates')
    op.drop_index(op.f('ix_communication_templates_channel'), table_name='communication_templates')
    op.drop_table('communication_templates')
    op.drop_table('whatsapp_configs')
    op.drop_table('phone_configs')
    # ### end Alembic commands ###
